services:
 dbpost:
  image: postgres:latest
  environment:
   POSTGRES_DB: db9testlab
   POSTGRES_USER: usr9testlab
   POSTGRES_PASSWORD: pass9testlab
  volumes:
   - ./init_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  ports:
   - 5432:5432
